### ISSUE TITLE
Cannot GET /bestblock

### ISSUE THREAD

**Issue by smithy9901** [Emurgo/yoroi-graphql-migration-backend#111]
Hi, the application does not respond correctly to any query

Example:
```
curl http://localhost:8082/bestblock/2
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /bestblock/2</pre>
</body>
</html>
```
```
curl http://localhost:8082/api/v2/bestblock
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v2/bestblock</pre>
</body>
</html>
```
And others from the documentation.

Config:
```
export default {
    db: {
      user: 'cardano',
      database: 'cexplorer',
      password: 'cardano',
      host: '127.0.0.1'
    },
    server: {
      addressRequestLimit: 50,
      apiResponseLimit: 50,
      graphqlEndpoint: 'http://localhost:3100/',
      txSubmissionEndpoint: 'https://backend.yoroiwallet.com/api/submit/tx',
      smashEndpoint: 'https://smash.yoroiwallet.com/api/v1/metadata/',
      port: 8082,
      txsHashesRequestLimit: 150
    }
  }
```

There are no errors in log files, nothing appears in them at all after launch 
```
> yoroi-cardano-backend@1.1.0 dev /opt/app
> tsc-watch --onSuccess "node ./dist/index.js"
1:30:16 PM - Starting compilation in watch mode...


1:30:20 PM - Found 0 errors. Watching for file changes.
listening on 8082...
(node:43) UnhandledPromiseRejectionWarning: error: column pool_hash.hash_raw does not exist
    at Parser.parseErrorMessage (/opt/app/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/opt/app/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/opt/app/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/opt/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:43) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

We use the latest version of the 'yoroi-graphql-migration-backend' compiled from the master of this repository today (10.11.2020).

What may be the problem and whether there are diagnostic tools?

**Comment by nicarq** [comment]
@smithy9901 what is the stack that you are running? are you running: cardano-node, cardano-db-sync and cardano-graphql?

**Comment by SebastienGllmt** [comment]
Looks like you're running an incompatible version of either cardano-db-sync or cardano-graphql. The field `hash_raw` was added in one of the latest versions. If you want to run master of this repository, you need to use commit bcd82d0a3eada57fdf7cc71670a46c9b3b80464f for cardano-db-sync and cardano-graphql 3.0.0

**Comment by smithy9901** [comment]
Hi, I updated the components and made a resync database, everything is in sync, but I get the same result.  

components:
```
docker.io/inputoutput/cardano-graphql:3.0.0
yoroi-graphql-migration-backend:1.1.1 (1.1.1 tag)
docker.io/hasura/graphql-engine:v1.3.2
docker.io/inputoutput/cardano-node:1.21.1
docker.io/inputoutput/cardano-db-sync:6.0.0
```

**Comment by nicarq** [comment]
Aha try with `curl http://167.71.98.122:8082/v2/bestblock` instead
