### ISSUE TITLE
/v2/txs/history  column "bytes" does not exist

### ISSUE THREAD

**Issue by matyushkins** [Emurgo/yoroi-graphql-migration-backend#112]
Hi 
ADA Back:
```
inputoutput/cardano-db-sync:6.0.0 
inputoutput/cardano-node:1.21.1
inputoutput/cardano-explorer-api:3.0.0
inputoutput/cardano-graphql:3.0.0
nputoutput/cardano-submit-api:3.0.0
inputoutput/cardano-graphql-hasura:3.0.0
```

```
ERROR url: /v2/txs/history
      stack: error: column "bytes" does not exist
    at Parser.parseErrorMessage (/home/guarda/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/home/guarda/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/home/guarda/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/home/guarda/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      message: column "bytes" does not exist
ERROR url: /v2/txs/history
      stack: error: column "bytes" does not exist
    at Parser.parseErrorMessage (/home/guarda/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/home/guarda/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/home/guarda/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/home/guarda/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      message: column "bytes" does not exist
```

**Comment by SebastienGllmt** [comment]
If you're trying to use cardano-db-sync, you need to use the release tag 1.1.1. found here: https://github.com/Emurgo/yoroi-graphql-migration-backend/releases

The latest master of this repository assumes you have cardano-db-sync commit bcd82d0a3eada57fdf7cc71670a46c9b3b80464f or later
