### ISSUE TITLE
'Configuration property "' + property + '" is not defined'

### ISSUE THREAD

**Issue by atomlab** [Emurgo/yoroi-graphql-migration-backend#16]
I have builded code from [839e597](https://github.com/Emurgo/yoroi-graphql-migration-backend/commit/839e59725ebee5e1420f252968d1f3a595c39b30). But startup failed.

```
# node index.js
WARNING: No configurations found in configuration directory:/opt/app/dist/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/opt/app/node_modules/config/lib/config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "server.graphqlEndpoint" is not defined
    at Config.get (/opt/app/node_modules/config/lib/config.js:182:11)
    at Object.<anonymous> (/opt/app/dist/utils/index.js:9:44)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/app/dist/index.js:42:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30
```

**Comment by SebastienGllmt** [comment]
Closing since I assume this has been resolved a long time ago
